#!/usr/bin/env python3
"""
Send Operational Validation Report v1 via Proton email

Purpose: Automate sending the report to your Proton email for review.
"""

import os
from pathlib import Path
from datetime import datetime

# Configuration
REPORT_PATH = "E:/Hermes Projects/personas/Operational-Validation-Report-v1.md"
SENDER_EMAIL = "yasaka.hanini@protonmail.com"  # Your Proton email
RECIPIENT_EMAIL = "yasaka.hanini@protonmail.com"  # Send to yourself for review
SUBJECT = "[HPF v2] Operational Validation Report v1 — Ready for Review"

# Read the report
with open(REPORT_PATH, 'r', encoding='utf-8') as f:
    report_content = f.read()

# Generate email body
email_body = f"""Hi,

The Operational Validation Report v1 has been automatically generated by the persona builder.

This marks the transition from architecture phase to operational validation phase.

## What was built:
- 5 personas across 4 domains (engineering, product, design, security)
- Validation log infrastructure with structured templates
- Automated persona builder script

## Next steps:
1. Review the report below
2. Execute scenarios for each persona using the CORE behavioural architecture
3. Fill validation logs with actual observations
4. Synthesise findings after 10+ persona evaluations

## Report:

{report_content}

---

This is an automated message from your automation architect.

Best,
Hermes
"""

# Write email to file (simulating email send)
email_path = Path("E:/Hermes Projects/personas/email-to-review.txt")
with open(email_path, 'w', encoding='utf-8') as f:
    f.write(f"From: {SENDER_EMAIL}\n")
    f.write(f"To: {RECIPIENT_EMAIL}\n")
    f.write(f"Subject: {SUBJECT}\n")
    f.write(f"Date: {datetime.now().strftime('%a, %d %b %Y %H:%M:%S %z')}\n")
    f.write("\n")
    f.write(email_body)

print("✅ Email prepared and saved to disk")
print(f"✅ Location: {email_path}")
print("✅ Ready to send via Proton web interface or email client")
print("\n--- Email Content Preview ---")
print(f"From: {SENDER_EMAIL}")
print(f"To: {RECIPIENT_EMAIL}")
print(f"Subject: {SUBJECT}")
print("\nBody preview:")
print(email_body[:500] + "...\n")
print("--- End Preview ---")

# Also save a summary
summary_path = Path("E:/Hermes Projects/personas/OPERATIONAL-VALIDATION-SUMMARY.txt")
with open(summary_path, 'w', encoding='utf-8') as f:
    f.write("=== OPERATIONAL VALIDATION SUMMARY ===\n\n")
    f.write("Automation Status: ✅ COMPLETE\n\n")
    f.write("Deliverables:\n")
    f.write("- 5 personas built across 4 domains\n")
    f.write("- Validation log infrastructure with templates\n")
    f.write("- Automated persona builder script\n")
    f.write("- Operational Validation Report v1 generated\n")
    f.write("- Email prepared for Proton review\n\n")
    f.write("Next Actions:\n")
    f.write("1. Review the Operational-Validation-Report-v1.md\n")
    f.write("2. Execute scenarios for each persona\n")
    f.write("3. Fill validation logs with actual observations\n")
    f.write("4. Synthesise findings after 10+ persona evaluations\n")
    f.write("5. Apply evidence threshold before considering architectural changes\n\n")
    f.write("Evidence Standard:\n")
    f.write("- One-off issue → document refinement\n")
    f.write("- Recurring issue across personas → candidate behavioural improvement\n")
    f.write("- Recurring issue with no owner → candidate architectural change\n")

print(f"\n✅ Summary saved to: {summary_path}")